name: Checkin

on:
  schedule:
    - cron: "45 2 * * *"  # 每天 02:45 定时运行
  workflow_dispatch:      # 手动触发工作流

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Auto Checkin for Traffic

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master               # 确保拉取的是 master 分支
          fetch-depth: 0            # 拉取完整的 Git 历史记录
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 认证

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"     # 使用 Python 3.x 最新版本
          architecture: "x64"

      # Step 3: Cache Python dependencies to speed up workflow
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies (if applicable)
      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Step 5: Run Python script for checkin
      - name: Run Checkin Script
        run: python ./.github/actions/checkin/universal.py

      # Step 6: Add Timestamp
      - name: Timestamp
        run: date
